version: "3.9"

services:

  hades:
    build: .
    container_name: hades-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: ${MONGO_URI}

  kong-database:
    image: postgres:13
    container_name: kong-db
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    ports:
      - "5432:5432"
    volumes:
      - kong-db-data:/var/lib/postgresql/data

  kong-migrations:
    image: kong:3.5
    container_name: kong-migrations
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PASSWORD: kong
    command: kong migrations bootstrap

  kong:
    image: kong:3.5
    container_name: kong
    depends_on:
      - kong-database
      - kong-migrations
      - hades
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000" # Proxy del API Gateway
      - "8443:8443"
      - "8001:8001" # Panel administrador
    restart: always

volumes:
  kong-db-data:
